# Generated by Django 4.1.2 on 2023-03-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_programme_cover'),
        ('portfolio', '0002_document_individual_document_programme_and_more'),
    ]

    operations = [
    ]
